In [41]:
import numpy as np

In [47]:
A = np.array([[0,1],[2,3],[4,5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [48]:
B = np.array([[0,1,2,3],[4,5,6,7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [50]:
np.dot(A, B).max()

np.int64(47)